### ISSUE TITLE
Attempted to run on localhost and got this error message

### ISSUE THREAD

**Issue by grospy** [cosmicjs/simple-nextjs-blog#6]
<img width="743" alt="Screen Shot 2023-08-08 at 4 10 28 PM" src="https://github.com/cosmicjs/simple-nextjs-blog/assets/9787023/9d6dd287-e9d8-4e35-85c0-740225db8d81">
It throws this out despite yarn being installed, nodeJS latest version and VueJS being installed.

**Comment by tonyspiro** [comment]
This is a Next.js blog, you should not be using Vue. Closing this.
